### PR TITLE
Learn spells on level up - Updated 

### PR DESCRIPTION
**Pull request by klister803**
This is an update for the existing module
The need for update because some spells quoted in the file are incorrect
Thus teaching proc spells players and some used for testing
This update fixes the problem

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
It's a new module?

Can you improve the module readme (because I'm not sure what it does atm) and add some missing files  from https://github.com/azerothcore/skeleton-module/

But if I understand right, you fixed Conan's module? then you should instead create a pull request in the right repo and I will merge it. We have a tutorial on how to open pull requests

**Comment by klister803** [comment]
@BarbzYHOOL Sorry, yes this is a fix, i could not do a pr on his repo (dunno why) i'm new to this, sorry.

**Comment by BarbzYHOOL** [comment]
ask me on discord i'll teach you

**Comment by BarbzYHOOL** [comment]
https://github.com/azerothcore/mod-learn-spells/pull/2

**Pull request closed without merging**
