### PR TITLE
create mod-top-arena

### PR DESCRIPTION
**Pull request by milestorme**
finished module ready for azerothcore

### CODE REVIEW

**Comment by milestorme** [comment]
@Helias here's mod-top-arena all cleaned up and ready to merge

**Comment by Helias** [comment]
Repo forked.

Add some icons into your modules to get a better visualization in the AzerothCore Catalogue :wink:

**Comment by milestorme** [comment]
ok ill do that, thank you , can you please enable travis for this module https://travis-ci.org/azerothcore/mod-top-arena

**Comment by Helias** [comment]
I can't.
@FrancescoBorzi

**Comment by FrancescoBorzi** [comment]
@Helias @milestorme done

**Comment by BarbzYHOOL** [comment]
nice

**Pull request merged**
